### ISSUE TITLE
restrict topology corruption in hwloc_filter_levels_keep_structure()

### ISSUE THREAD

**Issue by markalle** [open-mpi/hwloc#363] opened 2019-07-24 21:05 UTC
I tested this with hwloc-2.0.4

The "lstopo" command can be made to fail (segv) if you run in a cgroup that triggers the right path.

For me the following cgroup was able to fail:
% cgset -r cpuset.cpus=0,4,8,12,16,20 marktest
% cgexec -g cpuset:marktest /path/to/lstopo

This was on a ppc64le system with 2 sockets, 22 cores on each socket, and 4 hyperthreads on each core.

I added the following code to topology.c to look at the printout to identify when the topology tree is going bad

```
static void
check_obj_tree(hwloc_topology_t topology, hwloc_obj_t *pobj)
{
  static int depth = 0;
  ++depth;
  hwloc_obj_t obj = *pobj, child, *pchild;

  printf("[depth %d] chk obj=%p type=%d\n", depth, obj, (int)(obj->type));
  fflush(stdout);

  // if (depth >= 3) { -- depth; return; } // optional early return to only print part of tree
  for_each_child_safe(child, obj, pchild)
    check_obj_tree(topology, pchild);

  --depth;
}

And then throughout the code I call
    check_obj_tree(topology, &topology->levels[0][0]);
to see when the tree gets corrupted (some of the obj->type become garbage values)
```

And found it was the call to
```
        hwloc_free_unlinked_object(child);
```
where the hwloc_filter_levels_keep_structure() function frees a child that's apparently not completely removed from the tree.

The problem code seems to be in the section that starts out
```
    for(j=0; j<topology->level_nbobjects[i]; j++) {
      hwloc_obj_t parent = topology->levels[i-1][j];
      hwloc_obj_t child = topology->levels[i][j];
      unsigned k;
      if (replacechild) {
        /* move child's children to parent */
        parent->first_child = child->first_child;

        ... at the bottom of this section child gets freed
```

Where I get very confused is that the parent-child traversal seen by ```check_obj_tree(topology, &topology->levels[0][0]);``` isn't the same as what's shown by the ```for i ... for j ... parent=.. child=..``` code referenced above.

Here's an example output from check_obj_tree() from before I think any corruption happens:
```
[depth 1] chk obj=0x1d9804d0 type=0
[depth 2] chk obj=0x1d9b2510 type=12
[depth 3] chk obj=0x1d990d20 type=1
[depth 4] chk obj=0x1d9913e0 type=6
[depth 5] chk obj=0x1d991240 type=5
[depth 6] chk obj=0x1d9910a0 type=4
[depth 7] chk obj=0x1d990e20 type=2
... some sockets, cores, cache, etc below here making up a normal hwloc tree ...
[depth 2] chk obj=0x1d9b18e0 type=12
[depth 3] chk obj=0x1d9b0af0 type=13
[depth 2] chk obj=0x1d9b1ac0 type=12
[depth 3] chk obj=0x1d9b0d40 type=13
[depth 2] chk obj=0x1d9b1cd0 type=12
[depth 3] chk obj=0x1d9b0f90 type=13
[depth 2] chk obj=0x1d9b1ee0 type=12
[depth 3] chk obj=0x1d9b11e0 type=13
[depth 2] chk obj=0x1d9b20f0 type=12
[depth 3] chk obj=0x1d9b1430 type=13
[depth 2] chk obj=0x1d9b2300 type=12
[depth 3] chk obj=0x1d9b1680 type=13
```

This traversal thinks there are 7 OBJ_GROUP under the top OBJ_MACHINE, with the addresses being
```
machine at the top: 0x1d9804d0
child1 of type group: 0x1d9b2510
child2 of type group: 0x1d9b18e0
child3 of type group: 0x1d9b1ac0
```
And this traversal is based on using ```parent->first_child``` and ```child->next_sibling``` to walk the tree.

But that's not what the ```for i ... for j ...``` traversal in hwloc_filter_levels_keep_structure() seems to see.

The filter function's output shows
```
starts at level i=8, doesn't see any work to do there
goes on to level i=7
starts loop over j=0 (of 6) and sees
parent = 0x1d990e20 and child = 0x1d9b18e0 (types 2 and 12)
```

So it's about to remove child2 of the top level OBJ_MACHINE but the parent whose first_child it updates isn't the top level OBJ_MACHINE.  I think "parent" must mean something else in this context.

One thing I tried that appeared to work is add
```    child->prev_sibling->next_sibling = child->first_child;```
which seems to be the key location in the tree that a pointer to child exists and would otherwise continue to exist after child's removal.

I don't have high confidence in this fix though, because I'm finding the parent/child relationship in the i/j based traversal in hwloc_filter_levels_keep_structure() confusing and I guess there's something about the tree structure I don't understand.

**Comment by bgoglin** [comment] 2019-07-25 06:05
Can you post of tarball generated by hwloc-gather-topology inside that cgroup? I can't reproduce with fake topologies. If you can't post the tarball here, send it to me directly.
Did this happen in 2.0.3?

**Comment by markalle** [comment] 2019-07-25 18:43
Good idea, I had tried saving the topology as xml and using HWLOC_XMLFILE and didn't reproduce it either. It didn't take the same path. I think the original tree perhaps had 6 cores containing 6 groups containing 6 PUs and the function was collapsing out the intermediate level with 6 groups. But when reading from XML the tree probably didn't even have the extra level to be collapsed.

I can't completely run hwloc-gather-topology though, as "lstopo" segvs in the cgroup.  I hope it produced enough information though before that point.  (2.0.3 fails same as 2.0.4, I think the problem came in with hwloc-2)

I suspect any code that goes through the replacechild path in hwloc_filter_levels_keep_structure() will have a problem. I still don't understand the two different tree structures interacting, but I don't think the tree defined by traversing first_child and next_sibling is being maintained

I was about to attach the files but they're grayed out, not sure if that's a github security thing. So I'll mail them to you

**Comment by bgoglin** [comment] 2019-07-26 06:45
This should fix it:
```
diff --git a/hwloc/topology.c b/hwloc/topology.c
index 41f42a2c4..a13a94ee5 100644
--- a/hwloc/topology.c
+++ b/hwloc/topology.c
@@ -2342,6 +2342,8 @@ hwloc_compare_levels_structure(hwloc_topology_t topology, unsigned i)
     return -1;
 
   for(j=0; j<topology->level_nbobjects[i]; j++) {
+    if (topology->levels[i-1][j] != topology->levels[i][j]->parent)
+      return -1;
     if (topology->levels[i-1][j]->arity != 1)
       return -1;
     if (checkmemory && topology->levels[i-1][j]->memory_arity)
```
This was a rather strange but (passing --enable-debug made things obvious in debug messages). It was trying to merge the Core level with a Group level for CPU-less memory nodes. Those shouldn't be merged, obviously, because they are not parent/child (cores are inside a package while these groups are on the side). This is corner case that never happened before because the number of cores/groups was never the same, hence we never had to check parent/child.

**Comment by bgoglin** [comment] 2019-08-05 13:40
@markalle Can you confirm it solves your issue? If so, I'll push and you should likely backport it to OMPI too.

**Comment by markalle** [comment] 2019-08-09 05:26
Great news, I was able to test in both the whittled down environment that I reported here, as well as the larger environment where the issue was initially reported to me, and it's all working in both cases. Thanks

**Closed** 2019-08-09 06:57 UTC
