### ISSUE TITLE
netloc headers is missing from hwloc 2.9.1 include dir

### ISSUE THREAD

**Issue by torehl** [open-mpi/hwloc#589] opened 2023-05-23 17:21 UTC
### What version of hwloc are you using?

hwloc/gcc/2.9.1

* Run `which lstopo` to ensure that you are running the desired hwloc installation

torel@srl-login1:~/workspace/MPICH/4.1.1/mpich-4.1.1/Build-x86_64$ which lstopo
/cm/shared/apps/hwloc/gcc/2.9.1/bin/lstopo

* Run `lstopo --version` to find their hwloc version

torel@srl-login1:~/workspace/MPICH/4.1.1/mpich-4.1.1/Build-x86_64$ lstopo --version
lstopo 2.9.1

 * If hwloc was built from a Git clone, report the Git commit hash from `git show`

torel@srl-login1:~/workspace/hwloc/hwloc-2.9.1$ cat VERSION | egrep -e "major|minor|release" | head -5
# major, minor, and release are generally combined in the form
# <major>.<minor>.<release>.  If release is zero, then it is omitted.
major=2
minor=9
release=1

* If the hwloc error occured inside a non-hwloc process (e.g., MPI, SLURM, etc.), report the version of that software. Also try things like `ldd` on the program to find out which hwloc installation that software is using.

Built hwloc for mpich-4.1.1 compilation.  But when specifying -with-netloc it doesn't find netloc headers in "hwloc" directories.

### Which operating system and hardware are you running on?

* On Unix-like systems, run `uname -a` so that we know which operating system, distribution, and kernel version you are using.

torel@srl-login1:~/workspace/MPICH/4.1.1/mpich-4.1.1/Build-x86_64$ uname -a
Linux srl-login1 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

and same on Aarch64.

* Describe the machine and the processors it contains, as well as any memory and/or peripherals that matter to your issue

Dualprocessor Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz machine with T4 Grid GPU. A login node.

### Details of the problem

* What happened?

Expecting netloc headers to be installed in hwloc include directory or in a subdir of its include dir.

* How did you start your process?

Configuring MPICH 4.1.1 with netloc  (--with-netloc)

* How did it fail? Crash? Unexpected result?

Mpich 4.1.1 does not build as it is missing netloc headers in path.  Since hwloc includes both hwloc and netloc, you should also copy netloc headers into hwloc/gcc/4.1.1/include/ directory.  

torel@srl-login1:~/workspace/MPICH/4.1.1/mpich-4.1.1/Build-x86_64$ ll /cm/shared/apps/hwloc/gcc/2.9.1/include/
total 116
drwxr-xr-x 3 root root     46 May 23 17:38 ./
drwxr-xr-x 7 root root     92 May 23 17:38 ../
drwxr-xr-x 3 root root   4096 May 23 17:38 hwloc/   

`configure: ===== done with modules/json-c configure =====
checking hwloc.h usability... yes
checking hwloc.h presence... yes
checking for hwloc.h... yes
checking for hwloc_topology_set_pid in -lhwloc... yes
checking if hwloc meets minimum version requirement... yes
checking netloc.h usability... no
checking netloc.h presence... no
checking for netloc.h... no
configure: error: --with-netloc is given but not found
`

* If it crashed, please include a `gdb` backtrace if possible.
  * Passing `CFLAGS='-g -O0'` on the configure line may make the backtrace more useful.
  * Passing `--enable-debug` to the configure line should also enable lots of debug messages before the crash.

N/A 

### Additional information

N/A

**Comment by bgoglin** [comment] 2023-05-23 18:21
Netloc is dead, it has been unmaintained for years, and it will be removed in the upcoming hwloc 3.0. I hope MPICH doesn't really need it.
Your specific issue is likely caused by scotch not being available on your system. netloc scotch gets disabled by hwloc's configure, and netlocscotch.h is actually the only useful public headers for netloc (netloc.h contains nothing but error codes).

**Comment by bgoglin** [comment] 2023-06-08 07:52
Netloc was just removed from git master, I am closing this.

**Closed by bgoglin** 2023-06-08 07:52 UTC
