### ISSUE TITLE
Lowercase macros in rename.h

### ISSUE THREAD

**Issue by mcopik** [open-mpi/hwloc#229] opened 2017-02-17 17:43 UTC
I'm trying to build [HPX](https://github.com/STEllAR-GROUP/hpx) with both OpenMPI and hwloc. HPX utilizes CMake to find those libraries and generate build scripts. I'm using OpenMPI 1.10.4 on a university cluster. Hwloc is present as a library in the system but OpenMPI installation comes with its own build of hwloc. Our build scripts use this version automatically due to compilation flags extracted by CMake from OpenMPI installation:

```
/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/bin/mpicxx -showme:compile
-I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/hwloc/hwloc191/hwloc/include [...]
```

I assume here that the setup has been done correctly; please correct me if it's wrong and the scenario of including all hwloc headers should not happen. I have experienced quite weird linking errors until I have found out that rename macros are leaking from hwloc headers. In HPX we have a class [`hpx::threads::hwloc_topology`](https://github.com/STEllAR-GROUP/hpx/blob/ba6e693796bbad044ac41433737f7a11b6ebd905/hpx/runtime/threads/policies/hwloc_topology.hpp) and hwloc defines a rename [macro](https://github.com/open-mpi/ompi/blob/master/opal/mca/hwloc/hwloc1113/hwloc/include/hwloc/rename.h#L42) (!) with exactly the same name. I have confirmed that by running nm through our main library to find all relevant names changed, e.g.:
`0000000000752d90 T hpx::threads::opal_hwloc191_hwloc_topology::opal_hwloc191_hwloc_topology()`

If the OpenMPI has been set up correctly and it is expected that those headers may be included by other projects, then I think it is a bug. It is a very non-standard and even harmful practice to define preprocessor macro with lowercase letters. I believe it is a reasonable expectation that there are no reserved identifiers with "hwloc" in their name. I haven't found a list of prohibited identifiers in hwloc docs.

**Comment by bgoglin** [comment] 2017-02-17 19:15
I am not sure OpenMPI renamed hwloc headers are supposed to be included by other projects. I reassigned to @jsquyres since he knows about OMPI and since he was in charge of the renaming stuff.

The list of prohibited identifiers might be everything in hwloc/rename.h which means quite a lot, basically the entire API type and function names. But hwloc/rename.h is only enabled if HWLOC_SYM_TRANSFORM is defined, which is the case inside OMPI but certainly not by default.

**Comment by jsquyres** [comment] 2017-02-17 20:16
I'm curious how your `mpicc --showme:compile` got `-I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/hwloc/hwloc191/hwloc/include` -- that very much looks like an internal directory in the Open MPI source tree.  It should not be used by applications.

How did you build Open MPI?

**Comment by mcopik** [comment] 2017-02-17 22:24
@jsquyres Maybe it was not clear in my description - I'm working on a university cluster and OpenMPI is provided through modules. Another HPX user had [a similar problem](https://github.com/STEllAR-GROUP/hpx/issues/2410) few weeks ago where this include path appeared in compilation flags from OpenMPI. I can't say more than it was probably a different cluster but the OS and OpenMPI version is the same.

I can't do more than forward this problem to IT team at my university. If I understand you correctly, your suspicion here is that those flags should never appear in compilation flags and OpenMPI has been installed improperly?

**Comment by jsquyres** [comment] 2017-02-17 22:36
Yes, that `-I...hwloc191/hwloc/include` flag should never occur in a user installation when running `mpicc --showme:compile`.  That will give precedence to internal hwloc header files which contain the `rename.h` stuff, and will do the things that you describe (which are absolutely not meant for stuff outside the Open MPI source tree).  If this is happening, then either Open MPI was installed improperly or it is a real bug, and we should figure out how that is happening.

If your IT department can supply the `configure` line they used to build Open MPI, that would be great.

**Comment by mcopik** [comment] 2017-02-17 22:45
I'm going to create a ticket and ask them to provide us with a configure cmd as soon as possible.

I believe that using this compilation flag is also responsible for the problem of overriding default hwloc.h by the version from OpenMPI and causing [undefined references](https://github.com/STEllAR-GROUP/hpx/issues/2410) - I'm experiencing this problem as well.

**Comment by jsquyres** [comment] 2017-02-17 22:48
It quite definitely is.  If you can somehow override / remove that extra `-I` flag, you might be able to compile HPX successfully.

**Comment by mcopik** [comment] 2017-02-27 19:05
@jsquyres I received a reply from IT team. Their explanation is as follows: at least nine years ago they have decided to configure OpenMPI with option ` --with-devel-headers` because it was necessary for building parallel debugging plugins for Eclipse (PTP). They are investigating if this flag is still required but at that time it was mandatory. Quick googling reveals that the build process for PTP changed a [few years ago](https://wiki.eclipse.org/PTP/release_notes/2.1#Install_OpenMPI).

I've notified IT Center that at least for Eclipse PTP it is not necessary to use this flag. Though I can't tell if this requirement does not show up for other tools.

**Comment by ggouaillardet** [comment] 2017-03-02 12:44
@mcopik if hwloc is to be used by Open MPI and something else, then the best way is to build Open MPI with an external hwloc, and then build your app with the same hwloc.
for example, configure Open MPI with
```configure --with-hwloc=/opt/hwloc-v1.11 ...```
there can be some bad interaction between the internal and the external hwloc.
fwiw, we will stop embedding hwloc in the future in order to avoid these kind of bad interactions.

**Comment by mcopik** [comment] 2017-03-02 12:49
@ggouaillardet The local IT team has already decided to build all future releases of OpenMPI without `--with-devel-headers` which solves the problem for me. 

Thanks for the suggestion, it may be useful for people who still need devel headers for some reason.

**Comment by ggouaillardet** [comment] 2017-03-02 12:56
@mcopik cool, thanks for the report.
if you experience some issues at runtime that make very little sense, then keep in mind the root cause could be a bad interaction between internal ompi hwloc and the external hwloc used by your library.

**Comment by jsquyres** [comment] 2017-03-02 13:41
To follow up on what @ggouaillardet said:

1. Someday we will stop embedding hwloc.  For the moment, it's still going to be there, though.
1. @ggouaillardet is correct that the interaction between the internal and an external hwloc *can* cause problems.  But it usually shouldn't (because we name-shifted all the internal symbols).  If it does, @ggouaillardet is correct: that's a bug and you should contact us.
1. The `--with-devel-headers` option is really only intended for developers who are building Open MPI components out of tree.  It is not really intended for end users (e.g., we don't even document it in the README file).  I'm glad that the Eclipse project relaxed this requirement, but even if they didn't, I would not advocate for putting a `--with-devel-headers` installation into general production for exactly the kind of reasons you ran into (i.e., it exposes internal Open MPI header files that should not be seen by end users).

It seems like this issue is now resolve; I'm going to close it.  Thanks!

**Closed by jsquyres** 2017-03-02 13:41 UTC
