### ISSUE TITLE
Topology incorrect when CPU 0 offline

### ISSUE THREAD

**Issue by gmclay** [open-mpi/hwloc#450] opened 2021-02-05 19:18 UTC
### What version of hwloc are you using?
Issue reproduced in hwloc-2.4.1rc2 and hwloc-2.0.3

### Which operating system and hardware are you running on?
`uname -a`
Linux ubuntucpu0 4.15.18-custom #1 SMP Mon Feb 3 13:48:51 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
Note, custom kernel that allows offline CPU 0.

`cat /etc/os-release`
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Details of the problem
If CPU 0 is offline (disabled), hwloc topology is incorrect. Incorrect topology appears to have wrong hierarchy specifically related to an L3 cache.

By comparing topology.xml files generated in the following conditions, the issue can be seen.
- CPU 0 offline
- CPU 0 online
- CPU 1 offline
- CPU 1 online (same condition as CPU 0 online)

Attached are the topology files for the conditions above. Note how "topology_core0disabled_hwloc2.4.1rc2.xml" differs from all other .xml files (especially "topology_core1enabled_hwloc2.4.1rc2.xml").

CPU's can be "offlined" manually by editing "/sys/devices/system/cpu/cpuX/online" where X is the desired CPU #. The "online" file will contain a "1" if the CPU is online and "0" of the CPU is offline.

Images below generated from lstopo (lstopo -i .xml --ouput-format png) and respective topology XML files. Note, all three are from the same system. Variable is which (if any) CPUs are disabled.

**All cores online (conditions "CPU 0 online" and "CPU 1 online")** -- looks as expected
![topology_core0enabled_hwloc2 4 1rc2](https://user-images.githubusercontent.com/44707475/107078003-88a7e700-67a2-11eb-985c-5e31d9d477cf.png)

**CPU 1 offline** -- looks as expected
![topology_core1disabled_hwloc2 4 1rc2](https://user-images.githubusercontent.com/44707475/107077947-6f069f80-67a2-11eb-9691-5862820f638e.png)

**CPU 0 offline** -- does not look as expected
![topology_core0disabled_hwloc2 4 1rc2](https://user-images.githubusercontent.com/44707475/107077919-644c0a80-67a2-11eb-851a-4ec8da13b123.png)

### Additional information
For hwloc-2.0.3 an error message is printed to standard error (see below). For hwloc-2.4.1rc2 no error is printed and program using hwloc hangs. Note, in both cases a topology.xml file is generated which contains the same root issue. I believe behavior beyond incorrect topology creation should be ignored since it may related to the application using hwloc and therefore is not the root issue. 

```
**************************************************************************** 
* hwloc 2.0.3rc2-git received invalid information from the operating system. 
* 
* L3 (cpuset 0x0000000c) intersects with Core (P#2 cpuset 0x00400004) without inclusion! 
* Error occurred in topology.c line 1386 * 
* The following FAQ entry in the hwloc documentation may help: 
* What should I do when hwloc reports "operating system" warnings? 
* Otherwise please report this error message to the hwloc user's mailing list, 
* along with the files generated by the hwloc-gather-topology script. 
* 
* hwloc will now ignore this invalid topology information and continue. 
****************************************************************************
```

[topology_cpu0_offline.zip](https://github.com/open-mpi/hwloc/files/5934711/topology_cpu0_offline.zip)

**Comment by bgoglin** [comment] 2021-02-06 09:17
My 5.10 kernel won't let me offline CPU0. Can you offline CPU0 on your machine, run "hwloc-gather-topology foo" and post the foo.tar.bz2 file here? (you may need to rename it because github doesn't tar.bz2 files) I'll be able to look at what your kernel actually exposes. Having no cache at all in here tells me that some kernel feature may be disabled entirely.

To clarify your hangs: lstopo completes successfully after exporting the XML or displaying the graphics, only your own app hangs.

**Comment by gmclay** [comment] 2021-02-08 18:21
To enable offlining CPU 0 you have to recompile the kernel and enable the config below. 

```
< # CONFIG_BOOTPARAM_HOTPLUG_CPU0 is not set
---
> CONFIG_BOOTPARAM_HOTPLUG_CPU0=y
```

I ran "hwloc-gather-topology" and have a .tar.gz to share. I don't believe there is any sensitive information in the output but to be safe I will send the results via email rather than posting on this forum.

As a note, below is the output from the hwloc-gather command. Looks like the same error as above.

```
sys_shc@ubuntucpu0:~/gclay/offline_test/hwloc_gather$ cat /sys/devices/system/cpu/cpu0/online
0
sys_shc@ubuntucpu0:~/gclay/offline_test/hwloc_gather$ hwloc-gather-topology foo
I/O files won't be saved (--io not given).
DMI files won't be saved (--dmi not given).

****************************************************************************
* hwloc 1.11.9 has encountered what looks like an error from the operating system.
*
* L3 (P#0 cpuset 0x000007c0) intersects with Core (P#2 cpuset 0x00000c00) without inclusion!
* Error occurred in topology.c line 1088
*
* The following FAQ entry in the hwloc documentation may help:
*   What should I do when hwloc reports "operating system" warnings?
* Otherwise please report this error message to the hwloc user's mailing list,
* along with the files generated by the hwloc-gather-topology script.
****************************************************************************
Topology files gathered in ./foo.tar.bz2 and kept in /tmp/tmp.7fBxFwUsT1/foo/
Expected topology output stored in ./foo.output
XML topology stored in in ./foo.xml

WARNING: Do not post these files on a public list or website unless you
WARNING: are sure that no information about this platform is sensitive.
```

Correct. The "lstopo" command runs fine and I am only using it to convert the topology.xml into a .png. The topology.xml is generated by the hwloc library referenced by my app. The hang is in my app but due to how hwloc handles CPU 0 offline.

**Comment by bgoglin** [comment] 2021-02-08 18:39
Ok, that's an easy bug in hwloc. We look at CPU0 to decide whether we should use /sys/bus/cpu or /sys/devices/system/cpu. In your case, we think none is available, and we just disable the entire sysfs discovery.

Not sure about your big warning, I don't get anything here, we'll see later.

I am going to fix this in 2.4.1rc3. If you need a fix immediately, let me know, I can send a quick patch. The proper fix requires to see if I can remove the entire /sys/bus/cpu code since it's not actually needed from what I understand. I will work on it tomorrow.

**Comment by gmclay** [comment] 2021-02-09 00:27
Thanks for the quick reply. When will 2.4.1rc3 be released?

If you have a patch I can test before, that would be great. I can confirm the patch solves the problem before the RC.

**Comment by bgoglin** [comment] 2021-02-09 09:04
Should be fixed with #451. A tarball will be available at https://ci.inria.fr/hwloc/job/basic/view/change-requests/job/PR-451/

**Comment by gmclay** [comment] 2021-02-09 19:44
Tested the fix and it worked! Thanks for the quick response. Looking forward to having the fix in hwloc-2.4.1rc3.

**CPU 0 offline** -- using PR 451
![topology_2 4 1rc3](https://user-images.githubusercontent.com/44707475/107418722-d9ce1880-6acb-11eb-8e1b-e693f8ffbeb9.png)

**Comment by bgoglin** [comment] 2021-02-10 06:43
Good, thanks. If you get a chance to run such a kernel on a non-sensitive machine, I'd like to include a regression test in our nightly tests (this would expose the contents of your /proc/cpuinfo and /sys to the public).

**Closed** 2021-02-10 08:12 UTC

**Comment by bgoglin** [comment] 2021-04-27 14:04
03bddd0037c62116d6171e4bf1fb72c48a57d825 added a testcase with both CPU#0 and NUMA#0 offline on Linux.
