### ISSUE TITLE
make check fail on mingw

### ISSUE THREAD

**Issue by 3rav** [open-mpi/hwloc#424] opened 2020-09-30 07:16 UTC
Hi,

Errors during testing, mingw64:

```
PASS: 8intel64-4n2t-memattrs.xml
PASS: 16amd64-8n2c-cpusets.xml
PASS: 16amd64-4distances.xml
PASS: 16amd64-4distances.console.output
PASS: 16em64t-4s2c2t.xml
PASS: 16em64t-4s2c2t-offlines.xml
PASS: 16em64t-4s2c2t.console.output
PASS: 16-2gr2gr2n2c+misc.xml
PASS: 16-2gr2gr2n2c+misc.console.output
FAIL: 16intel64-manyVFs.xml
PASS: 16intel64-manyVFs.console.output
PASS: 16intel64-manyVFs.console.nocollapse.output
FAIL: 24em64t-2n6c2t-pci.xml
PASS: 32em64t-2n8c2t-pci-noio.xml
FAIL: 32em64t-2n8c2t-pci-normalio.xml
FAIL: 32em64t-2n8c2t-pci-wholeio.xml
FAIL: 64intel64-3g2n+2n-irregulargroups+pci.xml
PASS: 64intel64-3g2n+2n-irregulargroups+pci.console.output
PASS: 8intel64-fakeKNL-A2A-hybrid.rootattachednumas.xml
PASS: 64intel64-fakeKNL-SNC4-hybrid.xml
FAIL: 96em64t-4n4d3ca2co-pci.xml
FAIL: 192em64t-12gr2n8c2t.xml
FAIL: 192em64t-24n8c2t.xml
PASS: fakeheterodistances.xml
FAIL: 8em64t-2p2ca2co-nonodesets.v1tov2.xml
FAIL: 8ia64-2n2s2c+1n.v1tov2.xml
PASS: 16amd64-4distances.v1tov2.xml
FAIL: 16amd64-4distances.v2tov1.xml
PASS: 2intel64-1n2c-numaroot.v1tov2.xml
FAIL: 28intel64-2p2g7c-CoDgroups.v1tov2.xml
FAIL: 28intel64-2p2g7c-CoD.nogroups.v1tov2.xml
PASS: 8intel64-fakeKNL-A2A-hybrid.rootattachednumas.v1tov2.xml
PASS: 8intel64-fakeKNL-A2A-hybrid.rootattachednumas.v2tov1.xml
PASS: 64intel64-fakeKNL-SNC4-hybrid.v1tov2.xml
PASS: 64intel64-fakeKNL-SNC4-hybrid.v2tov1.xml
============================================================================
Testsuite summary for hwloc 2.3.0
============================================================================
# TOTAL: 35
# PASS:  22
# SKIP:  0
# XFAIL: 0
# FAIL:  13
# XPASS: 0
# ERROR: 0
============================================================================
See tests/hwloc/xml/test-suite.log
Please report to https://github.com/open-mpi/hwloc/issues
============================================================================

```

**Comment by bgoglin** [comment] 2020-09-30 07:22
Hello
You should look at the log of one of these failures, for instance tests/hwloc/xml/24em64t-2n6c2t-pci.xml.log
I would guess it's a numeric format issue (dot vs comma decimal separator) caused by your Windows langage not being English (we don't know how to solve this properly, there's a workaround in #246 for fixing make check).
Brice

**Comment by bgoglin** [comment] 2020-10-30 09:17
I am closing this assuming this is a locale issue as explained above.

**Closed by bgoglin** 2020-10-30 09:17 UTC
